Examples:  Add pie and donut charts
Orange-OpenSource/ods-charts pull request #88
Opened 2024-01-24 16:38 UTC by louismaximepiton

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

NA

### Description

Added an example showing a pie and a donut charts.

Questions still to be answered: 
- Do we make several pages for these two kinds of charts or only one is enough ? If not, remove the `ods-donut-charts.png`.
- Not quite sure of the values I gave inside the examples. Need to be discussed or is it fine as a first draft ?

### Motivation & Context

These type of charts are considered as basic and are missing inside the doc.

### Types of change

- New feature (non-breaking change which adds functionality)

### Test checklist

Please check that the following tests projects are still working:

- [x] `docs/examples`
- [ ] `test/angular-ngx-echarts`
- [ ] `test/angular-tour-of-heroes`
- [ ] `test/html`
- [ ] `test/react`
- [ ] `test/vue`
- [ ] `test/examples/bar-line-chart`
- [ ] `test/examples/single-line-chart`
- [ ] `test/examples/timeseries-chart`

2024-03-04 09:00 UTC, jacques-lebourgeois commented
Hi, I push 3 commits, 2 suggestion and one enhancement.

Available to discuss about them :)

2024-03-12 09:46 UTC, louismaximepiton reviewed
I feel right with your changes, the display is great and as an alpha version it's fine to add some support to legend I think

2024-03-15 14:03 UTC, jacques-lebourgeois commented on docs/examples/index.js
> +    usedLegends = 'echarts';
I asked myself the question. 

If the aim is to limit specific dev, then it's better to use the default behaviour of Apache Echarts, provided that the design generated with Apache Echarts legends and adapted by ods-charts is considered satisfactory.

- To use ECharts legends: the look&feel is satisfactory
- To use ods-charts legends: behaviour at the limits of Apache Echarts can lead to the internal legends and the graphs being superimposed.

2024-03-15 14:05 UTC, jacques-lebourgeois commented on docs/examples/index.js
> +                    <option value="odscharts" >ods-charts legends</option>
There are three types of legend to manage.

NB: it should be possible to choose a legend type independently of the graph type, even if there is a default legend type for each graph type.

2024-04-05 13:23 UTC, jacques-lebourgeois commented
> #158 has been merged, please apply the same modifications here

Commited

2024-06-05 14:39 UTC, louismaximepiton commented on docs/examples/index.js
> +                    <option value="odscharts" >ods-charts legends</option>
Tackled by #244

2024-06-05 14:39 UTC, louismaximepiton commented on docs/examples/index.js
> +    usedLegends = 'echarts';
Tackled by #242

2024-06-05 14:48 UTC, louismaximepiton commented
Removed the work you did @jacques-lebourgeois since it'll be embedded in #242 and following PRs. I think it's ready for review.

Note: I've added the Orange legend look for now, but it'll have to be removed if the #242 is merged before or if the #242 is merged after, think about reverting https://github.com/Orange-OpenSource/ods-charts/pull/88/commits/780f2cb376e0ed3c0e427cf7150c6ce0d1ad59cd

2024-06-21 16:46 UTC, jacques-lebourgeois commented
I just push a commit for suggestion if you agree

2024-06-21 16:47 UTC, jacques-lebourgeois approved these changes

2024-06-27 13:18 UTC, nbossard commented
We are waiting for this feature for project Orange Money Pay Metrics...

2024-07-08 07:51 UTC, julien-deramond requested changes
Good job with this addition @louismaximepiton 
Few tiny things to change before accepting.
Please check https://github.com/Orange-OpenSource/ods-charts/pull/300 to see if there are other changes to do here while rebasing the branch ;)

2024-07-09 05:23 UTC, julien-deramond approved these changes
LGTM! Let's wait for the light design review, and then we can merge/release 🚀

2024-07-19 17:12 UTC, Franco-Riccitelli commented
Here are some design review comments for the Pie chart and Donut chart.
- The use of the "Default" colours looks good to me. I can see these are based on the ODS Categorical colours for data displays.
- The spacing between each of the segments in the charts is also very good.
- The padding on the tooltips is quite large. For the Donut this can sometimes result in the tooltip overlapping the value in the centre of the Donut (when the chart is reduced in size). I suggest trying to reduce the padding in the tooltip by about half and also reducing the vertical space between the text labels in the tooltip by about a half.
- When the charts are reduced in size, I also think the font size can be reduced for the legend and the text in the tooltip. I suggest trying 14px font size.
- The legend should align with the title and subtitle at the top.  
- The wrapping of the legend works well.

2024-07-22 07:18 UTC, julien-deramond commented
Thanks for the design review @Franco-Riccitelli 🙏 

> The padding on the tooltips is quite large.
> I suggest trying to reduce the padding in the tooltip by about half and also reducing the vertical space between the text labels in the tooltip by about a half.

The padding on the tooltips follows the standard from ODS. We did not initially notice the different specification hidden at https://design.orange.com/0c1af118d/p/714762-legends/t/page-714762-48288420-5. Should we adhere to this specification instead for all charts? If so, this adjustment can be addressed in a separate PR, as it impacts the global rendering for all charts.

> When the charts are reduced in size, I also think the font size can be reduced for the legend and the text in the tooltip. I suggest trying 14px font size.

We can implement this change in separate PRs since it affects the global rendering for all charts:
* One PR for adjusting the label font size to 14px at small breakpoints
* Another PR (linked to the previous feedback) for tooltip rendering adjustments

However, we need to determine the breakpoint at which the font size changes to 14px. Should this adjustment occur from tablet rendering to mobile (medium)?

> The legend should align with the title and subtitle at the top. At the moment, the legend is positioned slightly to the right.

According to the [ODS Design guidelines](https://design.orange.com/0c1af118d/p/714762-legends/t/page-714762-48288439-8), the legend should be vertical and positioned on the right-hand side of the donut/pie chart. This change is not included in the current PR because it depends on the merge of another PR ([PR #244](https://github.com/Orange-OpenSource/ods-charts/pull/244)). You can preview the updates in [this deployment](https://deploy-preview-244--ods-charts.netlify.app/use_cases/legends-holders).
Do you confirm this must be positioned on the right-hand side of the donut/pie chart?

2024-07-22 10:14 UTC, Franco-Riccitelli commented
In response to the questions to my review of the Donut and Pie charts:

The padding for the tooltip should be reduced for all chart usage. I understand this will be a separate PR as this impacts the global rendering, which totally makes sense.

Font size change: I think the 14px font change should occur from the tablet to mobile breakpoints.

Legend positioning: The legend positioning at the bottom of the Pie and Donut chart works well and should remain at the bottom. The only slight adjustment is the alignment of the Legend to the Title and Subtitle (see attached example). Regarding the guidelines, I will update the Data Display Guidelines to show that the legend can be positioned at the bottom of Donut and Pie charts.
<img width="414" alt="Screenshot 2024-07-22 at 10 30 38 AM" src="https://github.com/user-attachments/assets/3bed11cf-9852-4f5c-a86c-8a1cab0db052">

2024-07-26 06:20 UTC, julien-deramond commented
Thanks a lot for your feedback, @Franco-Riccitelli. 
We've addressed the specific points related to the donut/pie charts in this PR. The more general feedback will be managed separately. We plan to create dedicated issues for those and implement the modifications through separate PRs.

2024-07-26 06:40 UTC, merged

2024-07-26 07:32 UTC, nbossard commented
👏 good news